more configuration stuff, with the included "dummyconfig" can now compile and run standalone programs without installation or extra flags

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,14 +1,94 @@
 #!/bin/sh
 
-case $1 in
-  "") cc=cc;;
-   *) cc=$1;;
+configure_options="$*"
+prefix=/usr/local
+bindir=''
+libdir=''
+mandir=''
+manext=1
+cc='cc'
+
+# Parse command-line arguments
+
+while : ; do
+  case "$1" in
+    "") break;;
+    -prefix|--prefix)
+        prefix=$2; shift;;
+    -bindir|--bindir)
+        bindir=$2; shift;;
+    -libdir|--libdir)
+        libdir=$2; shift;;
+    -mandir|--mandir)
+        case "$2" in
+          */man[1-9ln])
+            mandir=`echo $2 | sed -e 's|^\(.*\)/man.$|\1|'`
+            manext=`echo $2 | sed -e 's/^.*\(.\)$/\1/'`;;
+          *)
+            mandir=$2
+            manext=1;;
+        esac
+        shift;;
+    *) echo "Unknown option \"$1\"." 1>&2; exit 2;;
+  esac
+  shift
+done
+
+# Sanity checks
+
+case "$prefix" in
+  /*) ;;
+   *) echo "The -prefix directory must be absolute." 1>&2; exit 2;;
 esac
-export cc
+case "$bindir" in
+  /*) ;;
+  "") ;;
+   *) echo "The -bindir directory must be absolute." 1>&2; exit 2;;
+esac
+case "$libdir" in
+  /*) ;;
+  "") ;;
+   *) echo "The -libdir directory must be absolute." 1>&2; exit 2;;
+esac
+case "$mandir" in
+  /*) ;;
+  "") ;;
+   *) echo "The -mandir directory must be absolute." 1>&2; exit 2;;
+esac
+
+# Generate the files
 
 cd config/auto-aux
-rm -f s.h m.h
-touch s.h m.h
+rm -f s.h m.h Makefile
+touch s.h m.h Makefile
+
+# Write options to Makefile
+
+echo "# generated by ./configure $configure_options" >> Makefile
+
+# Where to install
+
+echo "PREFIX=$prefix" >> Makefile
+case "$bindir" in
+  "") echo 'BINDIR=$(PREFIX)/bin' >> Makefile
+      bindir="$prefix/bin";;
+   *) echo "BINDIR=$bindir" >> Makefile;;
+esac
+case "$libdir" in
+  "") echo 'LIBDIR=$(PREFIX)/lib/zebra' >> Makefile
+      libdir="$prefix/lib/zebra";;
+   *) echo "LIBDIR=$libdir" >> Makefile;;
+esac
+case "$mandir" in
+  "") echo 'MANDIR=$(PREFIX)/man' >> Makefile
+      mandir="$prefix/man";;
+   *) echo "MANDIR=$mandir" >> Makefile;;
+esac
+echo "MANEXT=$manext" >> Makefile
+
+# Configure compiler to use in further tests
+
+export cc
 
 # Check the sizes of data types
 
@@ -19,17 +99,17 @@ case "$1,$2,$3" in
   4,8,8) echo "Wow! A 64 bit architecture!"
          echo "#define CAML_SIXTYFOUR" >> m.h;;
   8,*,*) echo "Wow! A 64 bit architecture!"
-         echo "Unfortunately, Caml Light does not handle the case"
+         echo "Unfortunately, Zebra does not handle the case"
          echo "sizeof(int) = 8."
-         echo "Caml Light won't run on this architecture."
+         echo "Zebra won't run on this architecture."
          exit 2;;
   *,4,8) echo "Wow! A 64 bit architecture!"
-         echo "Unfortunately, Caml Light cannot work in the case"
+         echo "Unfortunately, Zebra cannot work in the case"
          echo "sizeof(long) != sizeof(long *)."
-         echo "Caml Light won't run on this architecture."
+         echo "Zebra won't run on this architecture."
          exit 2;;
   ?,?,?) echo "This architecture seems to be neither 32 bits nor 64 bits."
-         echo "Caml Light won't run on this architecture."
+         echo "Zebra won't run on this architecture."
          exit 2;;
       *) echo "Unable to compile the test program."
          echo "Make sure the C compiler is properly installed."
@@ -77,7 +157,7 @@ case $? in
   1) echo "This is a little-endian architecture."
      echo "#undef CAML_BIG_ENDIAN" >> m.h;;
   2) echo "This architecture seems to be neither big endian nor little endian."
-     echo "Caml Light won't run on this architecture."
+     echo "Zebra won't run on this architecture."
      exit 2;;
   *) echo "Something went wrong during endianness determination."
      echo "You'll have to figure out endianness yourself"
@@ -102,7 +182,7 @@ case $status in
        echo "#define CAML_ALIGNMENT" >> m.h;;
     *) echo "Something went wrong during alignment determination."
        echo "I'm going to assume this architecture has alignment constraints."
-       echo "That's a safe bet: Caml Light will work even if it turns out that"
+       echo "That's a safe bet: Zebra will work even if it turns out that"
        echo "this architecture actually has no alignment constraints."
        echo "#define CAML_ALIGNMENT" >> m.h;;
 esac
@@ -114,7 +194,7 @@ case $? in
      echo "#define CAML_ALIGN_DOUBLE" >> m.h;;
   *) echo "Something went wrong during alignment determination for doubles."
      echo "I'm going to assume this architecture has alignment constraints over doubles."
-     echo "That's a safe bet: Caml Light will work even if it turns out that"
+     echo "That's a safe bet: Zebra will work even if it turns out that"
      echo "this architecture actually has no alignment constraints."
      echo "#define CAML_ALIGN_DOUBLE" >> m.h;;
 esac
@@ -305,6 +385,21 @@ if sh hasgot strerror; then
   echo "#define HAS_STRERROR" >> s.h
 fi
 
+# Finish generated files
+
 rm -f tst hasgot.c
-rm -f ../m.h ../s.h
-mv m.h s.h ..
+rm -f ../m.h ../s.h ../Makefile
+mv m.h s.h Makefile ..
+
+# Print a summary
+
+echo
+echo "** Configuration summary **"
+echo
+echo "Directories where Zebra will be installed:"
+echo "        binaries.................. $bindir"
+echo "        standard library.......... $libdir"
+echo "        manual pages.............. $mandir (with extension .$manext)"
+echo
+echo "** Zebra configuration completed successfully **"
+echo
