major upintegrate from deductive branch; appears to work, but will probably cause a few glitches

diff --git a/testsuite/makefiles/Makefile.okbad b/testsuite/makefiles/Makefile.okbad
--- a/testsuite/makefiles/Makefile.okbad
+++ b/testsuite/makefiles/Makefile.okbad
@@ -6,11 +6,11 @@ compile:
 	@for file in *.ml; do \
 	  printf " ... testing '$$file'"; \
 	  if [ `echo $$file | grep bad` ]; then \
-	    $(OCAMLC) -c -w a $$file 2> /dev/null && (echo " => failed" && exit 1) || echo " => passed"; \
+	    $(LLAMAC) -c -w a $$file 2> /dev/null && (echo " => failed" && exit 1) || echo " => passed"; \
 	  else \
-	    test -f `basename $$file ml`mli && $(OCAMLC) -c -w a `basename $$file ml`mli; \
-	    $(OCAMLC) -c -w a $$file 2> /dev/null || (echo " => failed" && exit 1); \
-	    test -f `basename $$file ml`reference && $(OCAMLC) `basename $$file ml`cmo && ./a.out > `basename $$file ml`result && (diff -q `basename $$file ml`reference `basename $$file ml`result || (echo " => failed" && exit 1)); \
+	    test -f `basename $$file ml`mli && $(LLAMAC) -c -w a `basename $$file ml`mli; \
+	    $(LLAMAC) -c -w a $$file 2> /dev/null || (echo " => failed" && exit 1); \
+	    test -f `basename $$file ml`reference && $(LLAMAC) `basename $$file ml`cmo && ./a.out > `basename $$file ml`result && (diff -q `basename $$file ml`reference `basename $$file ml`result || (echo " => failed" && exit 1)); \
 	    echo " => passed"; \
 	  fi; \
 	done
