upgrade tools dir and start working on llamadep

diff --git a/tools/make-package-macosx b/tools/make-package-macosx
--- a/tools/make-package-macosx
+++ b/tools/make-package-macosx
@@ -1,14 +1,25 @@
-#!/bin/bash
+#!/bin/sh
 
-# $Id: make-package-macosx,v 1.6 2008-01-25 14:13:36 doligez Exp $
+#########################################################################
+#                                                                       #
+#                            Objective Caml                             #
+#                                                                       #
+#          Damien Doligez, projet Moscova, INRIA Rocquencourt           #
+#                                                                       #
+#   Copyright 2003 Institut National de Recherche en Informatique et    #
+#   en Automatique.  All rights reserved.  This file is distributed     #
+#   under the terms of the Q Public License version 1.0.                #
+#                                                                       #
+#########################################################################
+
+# $Id: make-package-macosx 10448 2010-05-21 11:28:21Z doligez $
 
 cd package-macosx
-rm -rf camllight.pkg camllight-rw.dmg
+rm -rf ocaml.pkg ocaml-rw.dmg
 
-VERSION=`sed -n -e '/VERSION/s/.*"\([^"]*\)".*/\1/p' ../version.h`
-VERSION_MAJOR=${VERSION%%.*}
-tmp=${VERSION##*.}
-VERSION_MINOR=${tmp%%[^0-9]*}
+VERSION=`sed -e 1q ../VERSION`
+VERSION_MAJOR=`sed -n -e '1s/^\([0-9]*\)\..*/\1/p' ../VERSION`
+VERSION_MINOR=`sed -n -e '1s/^[0-9]*\.\([0-9]*\)[.+].*/\1/p' ../VERSION`
 
 cat >Description.plist <<EOF
   <?xml version="1.0" encoding="UTF-8"?>
@@ -19,9 +30,9 @@ cat >Description.plist <<EOF
           <key>IFPkgDescriptionDeleteWarning</key>
           <string></string>
           <key>IFPkgDescriptionDescription</key>
-          <string>The Caml Light compiler and tools</string>
+          <string>The Objective Caml compiler and tools</string>
           <key>IFPkgDescriptionTitle</key>
-          <string>Caml Light</string>
+          <string>Objective Caml</string>
           <key>IFPkgDescriptionVersion</key>
           <string>${VERSION}</string>
   </dict>
@@ -35,11 +46,11 @@ cat >Info.plist <<EOF
 <plist version="1.0">
 <dict>
         <key>CFBundleGetInfoString</key>
-        <string>Caml Light ${VERSION}</string>
+        <string>Objective Caml ${VERSION}</string>
         <key>CFBundleIdentifier</key>
-        <string>fr.inria.caml-light</string>
+        <string>fr.inria.ocaml</string>
         <key>CFBundleName</key>
-        <string>Caml Light</string>
+        <string>Objective Caml</string>
         <key>CFBundleShortVersionString</key>
         <string>${VERSION}</string>
         <key>IFMajorVersion</key>
@@ -74,14 +85,15 @@ mkdir -p resources
 
 #                                         stop here -> |
 cat >resources/ReadMe.txt <<EOF
-This package installs Caml Light version ${VERSION}.
-You need Mac OS X 10.5.x (Leopard), with X11 and the
-XCode tools (v3.x) installed.
+This package installs Objective Caml version ${VERSION}.
+You need Mac OS X 10.5.x (Leopard), with the
+XCode tools installed (v3.1.1 or later), and
+optionally X11.
 
 Files will be installed in the following directories:
 
 /usr/local/bin - command-line executables
-/usr/local/lib/caml-light - library and support files
+/usr/local/lib/ocaml - library and support files
 /usr/local/man - manual pages
 EOF
 
@@ -89,29 +101,29 @@ chmod -R g-w root
 sudo chown -R root:wheel root
 
 /Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker \
-  -build -p "`pwd`/camllight.pkg" -f "`pwd`/root/usr/local" \
-         -i "`pwd`/Info.plist" -d "`pwd`/Description.plist" -r "`pwd`/resources"
+  -build -p "`pwd`/ocaml.pkg" -f "`pwd`/root" -i "`pwd`/Info.plist" \
+  -d "`pwd`/Description.plist" -r "`pwd`/resources"
 
-size=`du -s camllight.pkg | cut -f 1`
+size=`du -s ocaml.pkg | cut -f 1`
 size=`expr $size + 8192`
 
-hdiutil create -sectors $size camllight-rw.dmg
-name=`hdid -nomount camllight-rw.dmg | grep Apple_HFS | cut -d ' ' -f 1`
-volname="Caml Light ${VERSION}"
+hdiutil create -sectors $size ocaml-rw.dmg
+name=`hdid -nomount ocaml-rw.dmg | grep Apple_HFS | cut -d ' ' -f 1`
+volname="Objective Caml ${VERSION}"
 newfs_hfs -v "$volname" $name
 hdiutil detach $name
 
-name=`hdid camllight-rw.dmg | grep Apple_HFS | cut -d ' ' -f 1`
+name=`hdid ocaml-rw.dmg | grep Apple_HFS | cut -d ' ' -f 1`
 if test -d "/Volumes/$volname"; then
-  ditto -rsrcFork camllight.pkg "/Volumes/$volname/camllight.pkg"
+  ditto -rsrcFork ocaml.pkg "/Volumes/$volname/ocaml.pkg"
   cp resources/ReadMe.txt "/Volumes/$volname/"
 else
-  echo 'Unable to mount the disk image as "/Volumes/'$volname'"' >&2
+  echo "Unable to mount the disk image as \"/Volumes/$volname\"" >&2
   exit 3
 fi
 open "/Volumes/$volname"
 sleep 2
 hdiutil detach $name
 
-rm -rf "camllight-${VERSION}.dmg"
-hdiutil convert camllight-rw.dmg -format UDZO -o "camllight-${VERSION}.dmg"
+rm -rf "ocaml-${VERSION}.dmg"
+hdiutil convert ocaml-rw.dmg -format UDZO -o "ocaml-${VERSION}.dmg"
